import test from 'node:test'; import assert from 'node:assert/strict';
import { createGoogleHandler } from '../api/auth/google.js'; import { createCallbackHandler } from '../api/auth/callback.js'; import { createLogoutHandler } from '../api/auth/logout.js'; import { createAccessTokenHandler } from '../api/google/access-token.js'; import { parseCookies } from '../lib/cookies.js'; import { verifyOAuthState, openSession } from '../lib/security.js';
const env={SESSION_SECRET:'q'.repeat(32),GOOGLE_CLIENT_ID:'client',GOOGLE_CLIENT_SECRET:'client-secret',GOOGLE_REDIRECT_URI:'https://app.test/api/auth/callback'};
function response(){return{headers:{},statusCode:200,setHeader(k,v){this.headers[k]=v;return this},status(n){this.statusCode=n;return this},json(v){this.body=v;return this},end(){return this}}}

test('Google authorization redirects with exact scopes and PKCE state cookie',async()=>{const res=response();await createGoogleHandler(env)({method:'GET',headers:{}},res);assert.equal(res.statusCode,302);const u=new URL(res.headers.Location);assert.equal(u.searchParams.get('scope'),'openid email profile https://www.googleapis.com/auth/drive.file');assert.equal(u.searchParams.get('code_challenge_method'),'S256');const cookie=res.headers['Set-Cookie'];assert.match(cookie,/oauth_state=/);assert.match(cookie,/HttpOnly/);const stateCookie=parseCookies(cookie).oauth_state;const payload=verifyOAuthState(stateCookie,u.searchParams.get('state'),env.SESSION_SECRET);assert.equal(payload.verifier.length>=43,true);});

test('callback validates state and PKCE, stores encrypted refresh token and email',async()=>{let tokenBody;const fetch=async(url,init)=>{if(String(url).includes('/token')){tokenBody=init.body;return new Response(JSON.stringify({access_token:'access',refresh_token:'refresh-secret'}),{status:200})}return new Response(JSON.stringify({email:'person@example.com',email_verified:true}),{status:200})};const loginRes=response();await createGoogleHandler(env)({method:'GET',headers:{}},loginRes);const authUrl=new URL(loginRes.headers.Location);const cookie=parseCookies(loginRes.headers['Set-Cookie']).oauth_state;const req={method:'GET',headers:{cookie:`oauth_state=${encodeURIComponent(cookie)}`},query:{code:'code',state:authUrl.searchParams.get('state')}};const res=response();await createCallbackHandler({env,fetch})(req,res);assert.equal(res.statusCode,302);assert.match(tokenBody,/code_verifier=/);const sessionValue=parseCookies(res.headers['Set-Cookie'][0]).session;assert.deepEqual(openSession(sessionValue,env.SESSION_SECRET),{refreshToken:'refresh-secret',email:'person@example.com'});assert.doesNotMatch(res.headers['Set-Cookie'][0],/refresh-secret/);});

test('callback rejects invalid state before token exchange',async()=>{let called=false;const res=response();await createCallbackHandler({env,fetch:async()=>{called=true}})({method:'GET',headers:{cookie:'oauth_state=x'},query:{code:'c',state:'bad'}},res);assert.equal(res.statusCode,400);assert.equal(called,false)});

test('logout clears session and requires same origin',async()=>{const handler=createLogoutHandler();let res=response();await handler({method:'POST',headers:{host:'app.test',origin:'https://evil.test'}},res);assert.equal(res.statusCode,403);res=response();await handler({method:'POST',headers:{host:'app.test',origin:'https://app.test','x-forwarded-proto':'https'}},res);assert.equal(res.statusCode,200);assert.match(res.headers['Set-Cookie'],/Max-Age=0/)});

test('access token endpoint refreshes from session without returning refresh token',async()=>{const {sealSession}=await import('../lib/security.js');const fetch=async()=>new Response(JSON.stringify({access_token:'picker-access',expires_in:3600}),{status:200});const req={method:'GET',headers:{host:'app.test',origin:'https://app.test','x-forwarded-proto':'https',cookie:`session=${encodeURIComponent(sealSession({refreshToken:'refresh-secret',email:'e@x.co'},env.SESSION_SECRET))}`}};const res=response();await createAccessTokenHandler({env,fetch})(req,res);assert.deepEqual(res.body,{accessToken:'picker-access',expiresIn:3600});assert.doesNotMatch(JSON.stringify(res.body),/refresh-secret/)});
