import {
  validateConfig, normalizeQuestionnaire, addBlock, addQuestion, deleteBlock, deleteQuestion,
  moveBlock, moveQuestion, updateBlock, updateQuestion, safeFilename, buildMarkdown, migrateState, batchBlobs, canRecord, geminiHeaders, isGeminiApiKey
} from './frontend-core.js';

const STORAGE = 'custdev-recorder-settings';
const GEMINI_SESSION_KEY = 'custdev-recorder-gemini-api-key';
const root = document.querySelector('#app');
const status = document.querySelector('#status');
let settings = loadSettings();
let draft = settings?.questionnaire || null;
let step = 0;
let session = null;
let publicConfig = null;
let geminiApiKey = sessionStorage.getItem(GEMINI_SESSION_KEY) || '';
let pickerReady;
const recording = { recorder: null, stream: null, chunks: [], blob: null, mime: '', startedAt: null, timer: null, block: 0, busy: false };

function loadSettings() { try { return migrateState(JSON.parse(localStorage.getItem(STORAGE))); } catch { return null; } }
function saveSettings(value) { settings = migrateState(value); if (!settings) throw new Error('Настройки неполные'); localStorage.setItem(STORAGE, JSON.stringify(settings)); }
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c])); }
function announce(message, error = false) { status.textContent = message; status.className = error ? 'status error' : 'status'; }
async function api(url, options = {}, timeout = 60000) {
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout);
  try {
    const response = await fetch(url, { ...options, signal: controller.signal });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.error?.message || body.error || `Ошибка ${response.status}`);
    return body;
  } catch (error) { if (error.name === 'AbortError') throw new Error('Сервер не ответил вовремя'); throw error; }
  finally { clearTimeout(timer); }
}
function header(subtitle = 'Полевой диктофон интервью') { return `<header><div class="brand"><span class="logo" aria-hidden="true">●</span><div><b>CustDev Recorder</b><small>${esc(subtitle)}</small></div></div><button class="icon-btn" id="settings" aria-label="Настройки">⚙</button></header>`; }
function bindSettings() { document.querySelector('#settings')?.addEventListener('click', renderSettings); }
function shell(content, actions = '') { root.innerHTML = `${header()}<main>${content}</main>${actions ? `<footer>${actions}</footer>` : ''}`; bindSettings(); }
function button(id, text, kind = 'primary', extra = '') { return `<button id="${id}" class="${kind}" ${extra}>${text}</button>`; }

async function checkSession() { try { session = await api('/api/auth/session', {}, 12000); } catch { session = null; } return session; }
async function start() { await checkSession(); if (canRecord(session,settings,geminiApiKey)) renderStart(); else { step = session ? (!settings?.folder ? 1 : !isGeminiApiKey(geminiApiKey) ? 2 : 3) : 0; renderOnboarding(); } }

function progress() { return `<ol class="steps" aria-label="Настройка"><li class="${step===0?'active':''}">Google</li><li class="${step===1?'active':''}">Папка</li><li class="${step===2?'active':''}">Gemini</li><li class="${step===3?'active':''}">Опросник</li><li class="${step===4?'active':''}">Проверка</li></ol>`; }
function renderOnboarding() {
  if (step === 0) return renderAuth();
  if (step === 1) return renderFolder();
  if (step === 2) return renderGeminiKey();
  if (step === 3) return renderImport();
  renderEditor(true);
}
function renderAuth() {
  shell(`${progress()}<section><p class="eyebrow">Шаг 1 из 5</p><h1>Подключите Google Drive</h1><p>Приложение сохраняет аудио и расшифровку только в выбранную вами папку. Доступ выдаётся через Google; токены не сохраняются в localStorage.</p><div class="notice">Записывайте интервью только с явного согласия собеседника. Аудио обрабатывается сервисом распознавания и загружается напрямую в ваш Google Drive.</div>${session ? `<p class="success">Подключено: ${esc(session.email)}</p>` : `<a class="button primary" href="/api/auth/google">Войти через Google</a>`}</section>`, session ? button('next','Продолжить') : button('retry','Проверить подключение','secondary'));
  document.querySelector(session ? '#next' : '#retry').onclick = async () => { announce('Проверяю подключение…'); if (await checkSession()) { step = 1; renderOnboarding(); } else announce('Google Drive пока не подключён', true); };
}
async function loadPicker() {
  if (!publicConfig) publicConfig = validateConfig(await api('/api/config'));
  if (!window.gapi) await new Promise((resolve, reject) => { const s=document.createElement('script'); s.src='https://apis.google.com/js/api.js'; s.onload=resolve; s.onerror=()=>reject(new Error('Не удалось загрузить Google Picker')); document.head.append(s); });
  if (!pickerReady) pickerReady = new Promise((resolve, reject) => window.gapi.load('picker', { callback: resolve, onerror: () => reject(new Error('Google Picker недоступен')) }));
  await pickerReady;
}
async function chooseFolder() {
  announce('Открываю Google Drive…');
  try {
    await loadPicker(); const token = await api('/api/google/access-token');
    const folder = await new Promise((resolve, reject) => {
      const view = new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);
      new google.picker.PickerBuilder().setDeveloperKey(publicConfig.googlePickerApiKey).setAppId(publicConfig.googleProjectNumber).setOAuthToken(token.accessToken).addView(view).setCallback(data => {
        if (data.action === google.picker.Action.PICKED) resolve(data.docs[0]);
        if (data.action === google.picker.Action.CANCEL) reject(new Error('Выбор папки отменён'));
      }).build().setVisible(true);
    });
    settings = { version: 2, folder: { id: folder.id, name: folder.name }, questionnaire: draft || { title:'', blocks:[] } };
    announce(`Выбрана папка «${folder.name}»`); renderFolder();
  } catch (error) { announce(error.message, true); }
}
function renderFolder() {
  shell(`${progress()}<section><p class="eyebrow">Шаг 2 из 5</p><h1>Куда сохранять интервью?</h1><p>Выберите папку в Google Drive. Приложение запомнит только её идентификатор и название.</p>${settings?.folder ? `<div class="selected"><b>${esc(settings.folder.name)}</b><small>Папка Google Drive выбрана</small></div>` : ''}${button('pick',settings?.folder?'Выбрать другую папку':'Выбрать папку')}</section>`, `${button('back','Назад','secondary')}${button('next','Продолжить','primary',settings?.folder?'':'disabled')}`);
  document.querySelector('#pick').onclick=chooseFolder; document.querySelector('#back').onclick=()=>{step=0;renderOnboarding();}; document.querySelector('#next').onclick=()=>{step=2;renderOnboarding();};
}
function renderGeminiKey() {
  shell(`${progress()}<section><p class="eyebrow">Шаг 3 из 5</p><h1>Подключите Google Gemini</h1><p>Введите собственный ключ Google Gemini API. Он используется для разбора опросника, расшифровки и сопоставления ответов.</p><label>Gemini API key<input id="gemini-key" type="password" autocomplete="off" spellcheck="false" value="${esc(geminiApiKey)}" placeholder="AIza…"></label><div class="notice">Ключ хранится только в sessionStorage этой вкладки: он не попадает в localStorage, Drive, Markdown или экспорт и очищается при закрытии вкладки/сеанса браузера. Вы можете заменить или удалить его в настройках. Запросы передаются этому серверу по тому же origin, затем только Google Gemini; Google может учитывать использование и списывать вашу квоту.</div></section>`,`${button('back','Назад','secondary')}${geminiApiKey?button('clear-key','Удалить ключ','danger'):''}${button('save-key','Сохранить для этой вкладки')}`);
  document.querySelector('#back').onclick=()=>{step=1;renderOnboarding();};
  document.querySelector('#clear-key')?.addEventListener('click',()=>{sessionStorage.removeItem(GEMINI_SESSION_KEY);geminiApiKey='';renderGeminiKey();announce('Ключ Gemini удалён',false);});
  document.querySelector('#save-key').onclick=()=>{const value=document.querySelector('#gemini-key').value.trim();if(!isGeminiApiKey(value))return announce('Введите действительный ключ Google Gemini API',true);sessionStorage.setItem(GEMINI_SESSION_KEY,value);geminiApiKey=value;step=3;renderOnboarding();};
}
function renderImport() {
  shell(`${progress()}<section><p class="eyebrow">Шаг 4 из 5</p><h1>Добавьте опросник</h1><p>Загрузите PDF, DOCX, TXT или MD (до 4 МБ) либо вставьте текст. Мы выделим блоки и вопросы — всё можно исправить на следующем шаге.</p><label class="drop">Файл опросника<input id="file" type="file" accept=".pdf,.docx,.txt,.md,application/pdf,text/plain,text/markdown"></label><label>Или вставьте текст<textarea id="questionnaireText" rows="9" placeholder="Название исследования\n\nБлок 1\n1. Первый вопрос?" spellcheck="true"></textarea></label><div class="row">${button('parse','Разобрать опросник')}${button('manual','Создать вручную','secondary')}</div></section>`, button('back','Назад','secondary'));
  document.querySelector('#back').onclick=()=>{step=2;renderOnboarding();}; document.querySelector('#manual').onclick=()=>{draft={title:'Новый опросник',blocks:[{id:'b1',title:'Первый блок',questions:[{id:'q1',text:'Новый вопрос'}]}]};step=4;renderOnboarding();};
  document.querySelector('#parse').onclick=async()=>{ const file=document.querySelector('#file').files[0], text=document.querySelector('#questionnaireText').value.trim(); if(!file&&!text)return announce('Выберите файл или вставьте текст',true); const btn=document.querySelector('#parse'); btn.disabled=true; announce('Разбираю опросник…'); try { let options; if(file){const data=new FormData();data.append('file',file);options={method:'POST',body:data};}else options={method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})}; options.headers={...(options.headers||{}),...geminiHeaders(geminiApiKey)}; const result=await api('/api/questionnaire/parse',options,120000); draft=normalizeQuestionnaire(result.questionnaire); step=4;renderOnboarding();announce(result.source==='fallback'?'Опросник разобран базовым алгоритмом — проверьте вопросы':'Опросник готов к проверке'); }catch(error){announce(error.message,true);btn.disabled=false;} };
}
function editorMarkup() {
  return `<label>Название опросника<input id="qtitle" value="${esc(draft.title)}"></label><div id="blocks">${draft.blocks.map((block,bi)=>`<article class="editor-block" data-block="${esc(block.id)}"><div class="editor-head"><input aria-label="Название блока" data-role="block-title" value="${esc(block.title)}"><div class="tools"><button data-action="block-up" aria-label="Поднять блок" ${bi===0?'disabled':''}>↑</button><button data-action="block-down" aria-label="Опустить блок" ${bi===draft.blocks.length-1?'disabled':''}>↓</button><button data-action="block-delete" aria-label="Удалить блок">×</button></div></div>${block.questions.map((q,qi)=>`<div class="question" data-question="${esc(q.id)}"><span>${qi+1}</span><div><textarea data-role="question-text" rows="2" aria-label="Текст вопроса">${esc(q.text)}</textarea><input data-role="question-hint" aria-label="Подсказка" placeholder="Подсказка (необязательно)" value="${esc(q.hint||'')}"></div><div class="tools vertical"><button data-action="question-up" aria-label="Поднять вопрос" ${qi===0?'disabled':''}>↑</button><button data-action="question-down" aria-label="Опустить вопрос" ${qi===block.questions.length-1?'disabled':''}>↓</button><button data-action="question-delete" aria-label="Удалить вопрос">×</button></div></div>`).join('')}<button class="text-btn" data-action="question-add">+ Добавить вопрос</button></article>`).join('')}</div>${button('add-block','+ Добавить блок','secondary')}`;
}
function captureEditor() {
  draft={...draft,title:document.querySelector('#qtitle')?.value||draft.title};
  document.querySelectorAll('.editor-block').forEach(el=>{const bid=el.dataset.block;draft=updateBlock(draft,bid,el.querySelector('[data-role=block-title]').value);el.querySelectorAll('.question').forEach(q=>{draft=updateQuestion(draft,bid,q.dataset.question,{text:q.querySelector('[data-role=question-text]').value,hint:q.querySelector('[data-role=question-hint]').value});});});
}
function renderEditor(onboarding=false) {
  shell(`${onboarding?progress():''}<section><p class="eyebrow">${onboarding?'Шаг 5 из 5':'Настройки'}</p><h1>Проверьте вопросы</h1><p>Вопросы показываются во время записи блоками. Измените порядок и формулировки.</p>${editorMarkup()}</section>`, `${button('back',onboarding?'Назад':'Отмена','secondary')}${button('save',onboarding?'Сохранить и начать':'Сохранить')}`);
  root.onclick=e=>{const action=e.target.dataset.action;if(!action)return;captureEditor();const b=e.target.closest('[data-block]'),q=e.target.closest('[data-question]');if(action==='block-up')draft=moveBlock(draft,b.dataset.block,-1);if(action==='block-down')draft=moveBlock(draft,b.dataset.block,1);if(action==='block-delete')draft=deleteBlock(draft,b.dataset.block);if(action==='question-add')draft=addQuestion(draft,b.dataset.block);if(action==='question-up')draft=moveQuestion(draft,b.dataset.block,q.dataset.question,-1);if(action==='question-down')draft=moveQuestion(draft,b.dataset.block,q.dataset.question,1);if(action==='question-delete')draft=deleteQuestion(draft,b.dataset.block,q.dataset.question);renderEditor(onboarding);};
  document.querySelector('#add-block').onclick=()=>{captureEditor();draft=addBlock(draft);renderEditor(onboarding);};
  document.querySelector('#back').onclick=()=>onboarding?(step=3,renderOnboarding()):renderSettings();
  document.querySelector('#save').onclick=()=>{try{captureEditor();draft=normalizeQuestionnaire(draft);saveSettings({...settings,questionnaire:draft});announce('Настройки сохранены');renderStart();}catch(error){announce(error.message,true);}};
}

function renderStart() {
  if(!canRecord(session,settings,geminiApiKey)){step=!session?0:!settings?.folder?1:!isGeminiApiKey(geminiApiKey)?2:3;return renderOnboarding();}
  shell(`<section><p class="eyebrow">Полевой диктофон интервью</p><h1>Новое интервью</h1><p>Запись идёт одним разговором. После остановки приложение распознает речь, сопоставит ответы с вопросами и сохранит аудио и Markdown в «${esc(settings.folder.name)}».</p><label>Проект<input id="project" autocomplete="organization" placeholder="Например, исследование доставки"></label><label>Собеседник<input id="interviewee" autocomplete="name" placeholder="Имя или код респондента"></label><div class="notice">Перед началом получите согласие на запись. Не закрывайте вкладку во время записи и обработки.</div></section>`,button('record','Начать запись'));
  document.querySelector('#record').onclick=beginRecording;
}
function pickMime(){return ['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg'].find(x=>window.MediaRecorder?.isTypeSupported(x))||'';}
async function beginRecording(){if(!isGeminiApiKey(geminiApiKey)){step=2;renderOnboarding();return announce('Добавьте ключ Gemini для этой вкладки',true);}const project=document.querySelector('#project').value.trim(),interviewee=document.querySelector('#interviewee').value.trim();if(!project||!interviewee)return announce('Укажите проект и собеседника',true);if(!await checkSession()){step=0;renderAuth();return announce('Сессия Google истекла. Войдите снова.',true);}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recording.stream=stream;recording.mime=pickMime();recording.chunks=[];recording.startedAt=new Date().toISOString();recording.project=project;recording.interviewee=interviewee;recording.block=0;recording.busy=false;recording.recorder=new MediaRecorder(stream,recording.mime?{mimeType:recording.mime,audioBitsPerSecond:48000}:{});recording.recorder.ondataavailable=e=>{if(e.data.size)recording.chunks.push(e.data);};recording.recorder.onstop=finishRecording;recording.recorder.onerror=()=>interruptRecording('Ошибка записи микрофона. Сохраните тишину вокруг и попробуйте снова.');stream.getTracks().forEach(track=>track.addEventListener('ended',()=>{if(recording.recorder?.state==='recording')interruptRecording('Микрофон отключён, запись была прервана.');},{once:true}));recording.recorder.start(15_000);window.addEventListener('beforeunload',guard);document.addEventListener('visibilitychange',visibilityWarning);renderLive();}catch(error){announce(error.name==='NotAllowedError'?'Разрешите доступ к микрофону':'Не удалось начать запись',true);}}
function visibilityWarning(){if(document.hidden&&recording.recorder?.state==='recording')announce('Не закрывайте и не выгружайте вкладку: запись может прерваться.',true);}
function interruptRecording(message){if(recording.busy)return;recording.busy=true;try{if(recording.recorder?.state!=='inactive')recording.recorder.stop();}catch{}recording.stream?.getTracks().forEach(x=>x.stop());clearInterval(recording.timer);announce(message,true);}
function guard(e){e.preventDefault();e.returnValue='';}
function renderLive(){const b=settings.questionnaire.blocks[recording.block];shell(`<section class="live"><div class="live-line"><span class="pulse"></span><b id="clock">00:00</b> Идёт запись</div><p class="eyebrow">Блок ${recording.block+1} из ${settings.questionnaire.blocks.length}</p><h1>${esc(b.title)}</h1><ol class="questions">${b.questions.map(q=>`<li><b>${esc(q.text)}</b>${q.hint?`<small>${esc(q.hint)}</small>`:''}</li>`).join('')}</ol></section>`,`${button('prev','Назад','secondary',recording.block?'':'disabled')}${button('next',recording.block===settings.questionnaire.blocks.length-1?'Завершить':'Дальше')}`);document.querySelector('#settings')?.remove();document.querySelector('#prev').onclick=()=>{recording.block--;renderLive();};document.querySelector('#next').onclick=()=>{if(recording.block<settings.questionnaire.blocks.length-1){recording.block++;renderLive();}else stopRecording();};clearInterval(recording.timer);const start=Date.parse(recording.startedAt);recording.timer=setInterval(()=>{const sec=Math.floor((Date.now()-start)/1000),el=document.querySelector('#clock');if(el)el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;},1000);}
function stopRecording(){if(recording.busy)return;recording.busy=true;document.querySelectorAll('button').forEach(x=>x.disabled=true);recording.recorder.stop();recording.stream.getTracks().forEach(x=>x.stop());clearInterval(recording.timer);document.removeEventListener('visibilitychange',visibilityWarning);}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(blob);});}
function renderProgress(text,detail='Это может занять несколько минут. Не закрывайте страницу.'){shell(`<section><div class="spinner" aria-hidden="true"></div><h1>${esc(text)}</h1><p>${esc(detail)}</p><progress id="progress" aria-label="Прогресс"></progress></section>`);document.querySelector('#settings')?.remove();}
async function finishRecording(){recording.blob=new Blob(recording.chunks,{type:(recording.mime||recording.recorder.mimeType||'audio/webm').split(';')[0]});if(recording.blob.size<512){window.removeEventListener('beforeunload',guard);return renderFailure('Запись получилась пустой. Проверьте микрофон.');}await runWorkflow();}
async function transcribeBatch(blob,index,total){for(let attempt=1;attempt<=3;attempt++){try{renderProgress(`Расшифровываю часть ${index+1} из ${total}`,`Обработано ${index} из ${total}. Не закрывайте страницу.`);const audio=await blobToBase64(blob);return await api('/api/transcribe',{method:'POST',headers:{'Content-Type':'application/json',...geminiHeaders(geminiApiKey)},body:JSON.stringify({audio,mimeType:recording.blob.type})},120000);}catch(error){if(attempt===3)throw error;await new Promise(resolve=>setTimeout(resolve,attempt*1000));}}}
async function runWorkflow(){if(!isGeminiApiKey(geminiApiKey)){step=2;renderOnboarding();return announce('Добавьте ключ Gemini для продолжения обработки; запись сохранена в этой вкладке',true);}try{const batches=batchBlobs(recording.chunks,recording.blob.type);const parts=[];for(let i=0;i<batches.length;i++)parts.push((await transcribeBatch(batches[i],i,batches.length)).transcript);const transcribed={transcript:parts.join('\n').trim()};renderProgress('Разбираю ответы');const segmented=await api('/api/segment',{method:'POST',headers:{'Content-Type':'application/json',...geminiHeaders(geminiApiKey)},body:JSON.stringify({transcript:transcribed.transcript,questionnaire:settings.questionnaire})},120000);renderProgress('Загружаю аудио в Drive');const ext=recording.blob.type.includes('mp4')?'m4a':recording.blob.type.includes('ogg')?'ogg':'webm';const stem=`${recording.project} — ${recording.interviewee} — ${recording.startedAt.slice(0,19).replace(/[T:]/g,'-')}`;const audioName=safeFilename(stem,ext);const upload=await api('/api/upload-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folderId:settings.folder.id,filename:audioName,mimeType:recording.blob.type,size:recording.blob.size})});const put=await fetch(upload.uploadUrl,{method:'PUT',headers:{'Content-Type':recording.blob.type},body:recording.blob});if(!put.ok)throw new Error(`Google Drive не принял аудио (${put.status})`);const audioFile=await put.json();await api('/api/verify-upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folderId:settings.folder.id,fileId:audioFile.id})});renderProgress('Сохраняю расшифровку');const markdown=buildMarkdown({project:recording.project,interviewee:recording.interviewee,startedAt:recording.startedAt,questionnaire:settings.questionnaire,transcript:transcribed.transcript,segments:segmented.segments,audioFile});const docName=safeFilename(stem,'md');await api('/api/drive/save-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folderId:settings.folder.id,filename:docName,text:markdown})});window.removeEventListener('beforeunload',guard);recording.busy=false;renderSuccess(audioName,docName);}catch(error){recording.busy=false;renderFailure(error.message,true);}}
function renderSuccess(audioName,docName){shell(`<section><div class="result success-mark">✓</div><h1>Интервью сохранено</h1><p>В папке «${esc(settings.folder.name)}» созданы файлы:</p><ul><li>${esc(audioName)}</li><li>${esc(docName)}</li></ul></section>`,button('again','Новое интервью'));document.querySelector('#again').onclick=renderStart;}
function renderFailure(message,retry=false){shell(`<section><div class="result error-mark">!</div><h1>Не удалось завершить</h1><p>${esc(message)}</p><div class="notice">${recording.blob?'Запись остаётся в памяти этой вкладки. Не закрывайте её до повторной отправки.':'Начните новую запись после проверки микрофона.'}</div></section>`,`${retry?button('retry','Повторить'):''}${button('again','Начать заново','secondary')}`);document.querySelector('#retry')?.addEventListener('click',runWorkflow);document.querySelector('#again').onclick=()=>{if(recording.blob&&!confirm('Удалить несохранённую запись?'))return;window.removeEventListener('beforeunload',guard);renderStart();};}

function renderSettings(){shell(`<section><p class="eyebrow">Настройки</p><h1>CustDev Recorder</h1><div class="settings-list"><div><b>Google Drive</b><small>${session?esc(session.email):'Подключение не проверено'}</small><div class="row">${button('reconnect','Переподключить','secondary')}${button('logout','Выйти','danger')}</div></div><div><b>Gemini API</b><small>${isGeminiApiKey(geminiApiKey)?'Ключ доступен в этой вкладке':'Ключ не задан'}</small><div class="row">${button('gemini','Заменить ключ','secondary')}${isGeminiApiKey(geminiApiKey)?button('clear-gemini','Удалить ключ','danger'):''}</div></div><div><b>Папка</b><small>${esc(settings?.folder?.name||'Не выбрана')}</small>${button('folder','Изменить папку','secondary')}</div><div><b>Опросник</b><small>${esc(settings?.questionnaire?.title||'Не добавлен')}</small><div class="row">${button('edit','Редактировать','secondary')}${button('replace','Заменить','secondary')}</div></div><div><b>Локальные настройки</b><div class="row">${button('export','Экспорт JSON','secondary')}${button('reset','Сбросить','danger')}</div></div></div><div class="notice">Локально хранятся только название и ID папки и ваш опросник. Ключ Gemini хранится отдельно только в sessionStorage и очищается с сеансом вкладки; он не включается в экспорт. Google-токены находятся в защищённой серверной сессии.</div></section>`,button('close','Готово'));
  document.querySelector('#close').onclick=()=>canRecord(session,settings,geminiApiKey)?renderStart():(step=!session?0:!settings?.folder?1:!isGeminiApiKey(geminiApiKey)?2:3,renderOnboarding());document.querySelector('#reconnect').onclick=()=>location.href='/api/auth/google';document.querySelector('#logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});session=null;step=0;renderAuth();announce('Вы вышли из Google',false);}catch(e){announce(e.message,true);}};document.querySelector('#gemini').onclick=()=>{step=2;renderOnboarding();};document.querySelector('#clear-gemini')?.addEventListener('click',()=>{sessionStorage.removeItem(GEMINI_SESSION_KEY);geminiApiKey='';step=2;renderOnboarding();announce('Ключ Gemini удалён',false);});document.querySelector('#folder').onclick=()=>{step=1;renderOnboarding();};document.querySelector('#edit').onclick=()=>{draft=settings.questionnaire;renderEditor(false);};document.querySelector('#replace').onclick=()=>{step=3;renderOnboarding();};document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(settings,null,2)],{type:'application/json'}));a.download='custdev-recorder-settings.json';a.click();URL.revokeObjectURL(a.href);};document.querySelector('#reset').onclick=()=>{if(confirm('Удалить папку и опросник из этого браузера?')){localStorage.removeItem(STORAGE);settings=null;draft=null;step=session?1:0;renderOnboarding();}};
}

start().catch(error=>{announce(error.message,true);renderAuth();});
